language: java
sudo: true
dist: trusty
jdk: oraclejdk11

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2

services: mysql

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS meeting_project;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS meeting_project;'
  - mysql -e 'DROP DATABASE IF EXISTS meeting_project_test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS meeting_project_test;'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - juliaborovets2001@gmail.com
    on_failure: always
