language: java
sudo: true
dist: trusty
jdk: oraclejdk11

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - juliaborovets2001@gmail.com
    on_failure: always
